name: CDK Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/cdk/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/cdk/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build CDK package
        run: pnpm --filter cdk build

      - name: Run unit tests (Lambda)
        run: pnpm --filter cdk test:lambda

      - name: Run unit tests (Stack)
        run: pnpm --filter cdk jest test/cdk.test.ts test/cdk-stack.test.ts

      - name: Run integration tests
        run: pnpm --filter cdk test:integration